services:
  namenode:
    build: ./namenode
    image: hadoop-namenode:1.0.0
    container_name: namenode
    volumes:
      - /bigdata/hadoop_namenode:/hadoop/dfs/name
      - ./data/:/hadoop-data/input
      - ./map_reduce/:/hadoop-data/map_reduce
      - ./requirements.txt:/hadoop-data/requirements.txt
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020
    networks:
      - hadoop_network

  resourcemanager:
    build: ./resourcemanager
    image: hadoop-resourcemanager:1.0.0
    container_name: resourcemanager
    restart: on-failure
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    ports:
      - 8089:8088
    networks:
      - hadoop_network

  historyserver:
    build: ./historyserver
    image: hadoop-historyserver:1.0.0
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - /bigdata/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188
    networks:
      - hadoop_network

  nodemanager1:
    build: ./nodemanager
    image: hadoop-nodemanager:1.0.0
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    volumes:
      - /bigdata/hadoop_namenager_local:/hadoop/dfs/local
      - /bigdata/hadoop_namenager_logs:/hadoop/dfs/logs
    ports:
      - 8042:8042
    networks:
      - hadoop_network

  datanode1:
    build: ./datanode
    image: hadoop-datanode1:1.0.0
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - /bigdata/hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  datanode2:
    build: ./datanode
    image: hadoop-datanode2:1.0.0
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - /bigdata/hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
  datanode3:
    build: ./datanode
    image: hadoop-datanode3:1.0.0
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - /bigdata/hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

networks:
  hadoop_network:
    name: hadoop_network
    external: true