x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-airflow-hadoop-base:3.3.6}
  environment:
    - AIRFLOW_HOME=/home/airflow
    - AIRFLOW__CORE__DAGS_FOLDER=/home/airflow/dags
    - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    # - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
    - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
  volumes:
    - /bigdata/airflow/output:/home/airflow/output
    - ./dags:/home/airflow/dags
    - /bigdata/airflow/plugins:/home/airflow/plugins
    - /bigdata/airflow/logs:/home/airflow/logs
    - /bigdata/airflow/logs/scheduler:/home/airflow/logs/scheduler
    - ./data/:/hadoop-data/input
    - ./map_reduce/:/hadoop-data/map_reduce
  depends_on:
    - postgres
    - redis
  networks:
    - hadoop_network

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - hadoop_network

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - hadoop_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init && airflow db upgrade && airflow users create --role Admin --username airflow --password airflow --email airflow@airflow.com --firstname airflow --lastname airflow )
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always

  airflow-worker-1:
    <<: *airflow-common
    command: airflow celery worker
    container_name: airflow_worker_1
    restart: always

  airflow-worker-2:
    <<: *airflow-common
    command: airflow celery worker
    container_name: airflow_worker_2
    restart: always
  
  airflow-flower:
    <<: *airflow-common
    command: airflow celery flower
    ports:
      - 5555:5555
    container_name: airflow_flower
    restart: always

networks:
  hadoop_network:
    name: hadoop_network
    external: true