services:
  hive-server:
    image: hadoop-spark-java-python-hive-server:3.3.6-3.1.3
    container_name: hive-server
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://postgresdb:5432/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    volumes:
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    restart: always
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - hadoop_network

  hive-metastore:
    image: hadoop-spark-java-python-hive-server-metastore:3.3.6-3.1.3
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864  postgresdb:5432"
    volumes:
      - ./hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    ports:
      - "9083:9083"
    networks:
      - hadoop_network

networks:
  hadoop_network:
    external: true