services:
  spark-master:
    image: spark-base:3.5.1
    container_name: spark-master
    ports:
      - 9089:8081
      - 7077:7077
    volumes:
      - /home/bdata/bigdata-file/spark/apps:/opt/spark-apps
      - /home/bdata/bigdata-file/spark/data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  spark-worker-a:
    image: spark-base:3.5.1
    container_name: spark-worker-a
    ports:
      - 9091:8081
      - 7000:7000
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - /home/bdata/bigdata-file/spark/apps:/opt/spark-apps
      - /home/bdata/bigdata-file/spark/data:/opt/spark-data
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  spark-worker-b:
    image: spark-base:3.5.1
    container_name: spark-worker-b
    ports:
      - 9092:8081
      - 7001:7000
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - /home/bdata/bigdata-file/spark/apps:/opt/spark-apps
      - /home/bdata/bigdata-file/spark/data:/opt/spark-data
    networks:
      - hadoop_network
    command: /bin/sh -c "./start-spark.sh"

  livy:
    build: ./livy
    image: livy:1.0.0
    restart: always
    container_name: livy
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    depends_on:
      - spark-worker-a
      - spark-worker-b
    ports:
      - 8998:8998
      - 4040:4040
    environment:
      - SPARK_MASTER_ENDPOINT=spark-master
      - SPARK_MASTER_PORT=7077
      - DEPLOY_MODE=client
    healthcheck:
      test: [ "CMD", "nc", "-z", "livy", "8998" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - hadoop_network

networks:
  hadoop_network:
    name: hadoop_network
    external: true
